# Generated by Django 2.0.2 on 2018-04-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20180427_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='type',
            new_name='category',
        ),
    ]
