# Generated by Django 2.0.2 on 2018-04-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_auto_20180404_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='district',
            name='slug',
        ),
    ]
