# Generated by Django 2.0.2 on 2018-04-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_auto_20180404_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='A photo of the piece of land',
            new_name='photo',
        ),
    ]
