# Generated by Django 2.0.2 on 2018-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_auto_20180412_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='Title number',
            new_name='title_number',
        ),
    ]
